"""Configuration settings for the TTS package."""

from .settings import (
    OutputMode, DEFAULT_SAMPLE_RATE, DEFAULT_VOICE,
    DEFAULT_SPEED, DEFAULT_SENTENCES_PER_CHUNK,
    DEFAULT_EXAGGERATION, DEFAULT_CFG_WEIGHT,
    LANGUAGE_CODES
)

__all__ = [
    "OutputMode", "DEFAULT_SAMPLE_RATE", "DEFAULT_VOICE",
    "DEFAULT_SPEED", "DEFAULT_SENTENCES_PER_CHUNK",
    "DEFAULT_EXAGGERATION", "DEFAULT_CFG_WEIGHT",
    "LANGUAGE_CODES"
] 